feat: Add new field non_os_package_support to ghcr resource
lacework/terraform-provider-lacework pull request #178
Opened 2021-09-28 14:16 UTC by dmurray-lacework

***Issue***: https://lacework.atlassian.net/browse/ALLY-663

***Description:***
Add new field non_os_package_support for ghcr terraform resource

Signed-off-by: Darren Murray <darren.murray@lacework.net>

2021-09-28 14:39 UTC, dmurray-lacework commented on integration/resource_lacework_integration_ghcr_test.go
> +		assert.Equal(t, false, updateData.Data.NonOSPackageEval)
```suggestion
		assert.Equal(t, true, updateData.Data.NonOSPackageEval)
```

2021-09-28 14:54 UTC, dmurray-lacework commented on vendor/github.com/lacework/go-sdk/api/container_registries_ghcr.go
> +	NonOSPackageEval 	  bool `json:"NON_OS_PACKAGE_EVAL,omitempty"`
```suggestion
	NonOSPackageEval 	  bool `json:"nonOsPackageEval,omitempty"`
```

2021-09-29 17:33 UTC, afiune requested changes

2021-09-29 17:33 UTC, afiune commented on examples/resource_lacework_integration_ghcr/variables.tf
> +variable "non_os_packages" {
Please update the rest and format all Terraform files
```suggestion
variable "non_os_package_support" {
```

2021-09-30 09:05 UTC, dmurray-lacework commented on integration/resource_lacework_integration_ghcr_test.go
> +				"non_os_packages": false,
```suggestion
				"non_os_package_support": false,
```

2021-09-30 09:05 UTC, dmurray-lacework commented on integration/resource_lacework_integration_ghcr_test.go
> +		terraformOptions.Vars["non_os_packages"] = true
```suggestion
		terraformOptions.Vars["non_os_package_support"] = true
```

2021-09-30 09:25 UTC, afiune approved these changes

2021-09-30 09:25 UTC, merged