feat: new lacework_query resource
lacework/terraform-provider-lacework pull request #266
Opened 2022-02-14 14:33 UTC by dmurray-lacework

***Issue***: https://lacework.atlassian.net/browse/ALLY-870

***Description:***
Add new resource `lacework_query`

Usage:
```hcl 
 resource "lacework_query" "example" {
    query_id       = var.query_id
    evaluator_id   = "Cloudtrail"
    query          = var.query
  }
  ```

2022-02-14 17:21 UTC, afiune commented on examples/resource_lacework_query/main.tf
> +    {
This type of query won't work until we release the feature request to have anonymous queries.

2022-02-15 09:00 UTC, afiune commented on website/docs/r/query.html.markdown
> +A Lacework query can be imported using a `QUERY_ID`, e.g.
Please, add the CLI commands to list queries:
```
lacework query list
```

2022-02-16 16:48 UTC, hazedav commented on examples/resource_lacework_query/main.tf
> +  resource "lacework_query" "example" {
nit. Is there a leading space here?

2022-02-16 16:48 UTC, hazedav commented on examples/resource_lacework_query/main.tf
> +    query          = var.query
nit.  should we call this query_text to be consistent with Lacework APIs and SDK structs?

2022-02-16 16:50 UTC, hazedav approved these changes
Approved w/ comments.

2022-02-17 07:42 UTC, afiune commented on examples/resource_lacework_query/main.tf
> +  resource "lacework_query" "example" {
yes, let's format this file, please.

2022-02-17 07:52 UTC, afiune requested changes
Unfortunately, when we do not specify an evaluator ID, the platform  returns the string `"<<IMPLICIT>>"` which causes a constant drift. 

![Screen Shot 2022-02-16 at 11 50 57 PM](https://user-images.githubusercontent.com/5712253/154429889-510eb01f-806c-4158-aa61-009264cf6598.png)

How do we address this @dmurray-lacework @hazedav ?

2022-02-17 11:44 UTC, dmurray-lacework commented
> Unfortunately, when we do not specify an evaluator ID, the platform returns the string `"<<IMPLICIT>>"` which causes a constant drift.
> 
> ![Screen Shot 2022-02-16 at 11 50 57 PM](https://user-images.githubusercontent.com/5712253/154429889-510eb01f-806c-4158-aa61-009264cf6598.png)
> 
> How do we address this @dmurray-lacework @hazedav ?

We could set a default value of "<<IMPLCIT>>" in the schema. 
Or a diffsupressfunc

I'll take a look at this today

2022-02-17 17:37 UTC, afiune requested changes

2022-02-17 17:37 UTC, afiune commented on lacework/resource_lacework_query.go
> +	d.SetId(response.Data.QueryID)
I don't think ID's can be changed, lets's not "update" it
```suggestion
```

2022-02-17 17:37 UTC, afiune commented on lacework/resource_lacework_query.go
> +	d.SetId(response.Data.QueryID)
I also don't think that Read should set the ID. I just went and looked and other resources in our codebase have this pattern but it is wrong.
```suggestion
```

2022-02-17 17:37 UTC, afiune commented on website/docs/r/query.html.markdown
> +  query_id       = Lql_Terraform_Query
```suggestion
  query_id       = "Lql_Terraform_Query"
```

2022-02-17 17:37 UTC, afiune commented on website/docs/r/query.html.markdown
> +## Example Usage
I wish we could add at least two examples, one that doesn't have evaluator ID and another one that NEEDS this evaluator ID and explain why the user needs it.

2022-02-23 08:11 UTC, afiune approved these changes
Two comments but out of that...

![tenor-128082851](https://user-images.githubusercontent.com/5712253/155281777-a6bece02-bb7b-4b07-b243-eb6fbd97a6d3.gif)

2022-02-23 08:11 UTC, afiune commented on lacework/resource_lacework_query.go
> +					return old == "<<IMPLICIT>>" || new == "<<IMPLICIT>>"
I'm not sure that after this we could change the evaluator ID but I also think those are edge cases where the user wants to repurpose a query, so let us ignore this for now. 😅

2022-02-23 12:17 UTC, dmurray-lacework commented on lacework/resource_lacework_query.go
> +	if d.HasChange("query_id") {
I can't find a way to check the diff between old and new on validation.

2022-02-23 15:41 UTC, merged