feat: new lacework_alert_channel_gcp_pub_sub resource
lacework/terraform-provider-lacework pull request #58
Opened 2021-01-19 15:39 UTC by dmurray-lacework

Add new resource lacework_alert_channel_gcp_pub_sub

Signed-off-by: Darren Murray <darren.murray@lacework.net>

2021-01-19 19:48 UTC, scottford-lw commented
Great work @dmurray-lacework 👍

2021-01-19 19:48 UTC, scottford-lw approved these changes
👍

2021-01-20 03:29 UTC, afiune commented on lacework/resource_lacework_alert_channel_gcp_pub_sub.go
> +							Required: true,
This element **must** be marked as sensitive. Please check how this was implemented here https://github.com/lacework/terraform-provider-lacework/blob/master/lacework/resource_lacework_integration_gcp_cfg.go#L56-L73

2021-01-20 03:35 UTC, afiune commented on website/docs/r/alert_channel_gcp_pub_sub.html.markdown
> +* `topic_id` - (Required) The id of the Gcp Pub Sub Topic.
ID should be capitalized.
Google's doc refer to Pub/Sub topic: https://cloud.google.com/pubsub

```suggestion
* `topic_id` - (Required) The ID of the Google Cloud Pub/Sub topic.
```

2021-01-20 03:35 UTC, afiune commented on website/docs/r/alert_channel_gcp_pub_sub.html.markdown
> +* `project_id` - (Required) The name of the Gcp Project.
```suggestion
* `project_id` - (Required) The name of the Google Cloud Project.
```

2021-01-20 03:39 UTC, afiune commented on website/docs/r/alert_channel_gcp_pub_sub.html.markdown
> +  }
Could we please update three things here, the topic and project ids should be something meaningful. Also, let's use the same docs on the other resources for the `credentials` field here 👆🏽

2021-01-20 03:39 UTC, afiune requested changes
Some docs nitpick but one "must change" comment.

2021-01-20 16:03 UTC, afiune commented on lacework/resource_lacework_alert_channel_gcp_pub_sub.go
> +									"name", "resource_level", "resource_id", "org_level", "enabled",
```suggestion
									"name", "project_id", "topic_id", "org_level", "enabled",
```

2021-01-22 14:33 UTC, afiune approved these changes
![tenor-231096426](https://user-images.githubusercontent.com/5712253/105503575-fec92b80-5c83-11eb-9dea-1ba2556518ed.gif)

2021-01-22 14:47 UTC, merged